/**
 * Provides English labels.
 * 
 * Copyright 2018-2019 SLUB Dresden
 */
const Localization = (function (){
	const language = "en";
	
	const localizedStrings = {
		"keywords" : "Keywords",
		"yes" : "yes",
		"no" : "no",
		"from" : "from",
		"to" : "to",
		"actionmenu": "actions menu",
		
		"cookieInfo":"We apply cookies and other tracking techniques, in order to better understand how our web site is used and to present relevant and interesting content to our users. Thereby, no personal data is passed on to third parties.",
		
		"selectProperty": "Please select a material property...",
		
		"facets.showLess" : "show less",
		"facets.showMore" : "show {0} more",
		
		"ExportJSON": "export (JSON)",
		"ExportRDF": "export (RDF/XML)",
		"ExportCSV": "export (CSV)",
		
		"detailpage.classInfo": "Show informationen about the material class at {0}.",
		
		"ExportCSV.query": "Search query",
		"ExportCSV.heading": "Material name;company;detail page in the Material Hub",
		
		"emailTpl.subject": "Request regarding your material ",
		"emailTpl.body": "Dear Ladies and Gentlemen,\nwhile searching for suitable materials using the following criteria, I came across your product '{0}'.\n\n",
		"emailTpl.footer": "\n\nPlease contact me for an offer.\n\nYours sincerely,\n",
		
		"compView.property" : "Property",
		"compView.heading" : "Material comparison",
		"compView.back" : "Back to material selection",
		"compView.close" : "close",
		"compViewPlot.selectProps" : "Select material properties for comparison:",
		
		"matClassSel.expand": "Show further subclasses",
		"matClassSel.collapse": "Hide subclasses",
		"matClassSel.goto": "Show the materials of class ",
		"matClassSel.navigate": "Show subclasses of ",
		
		"matSel.heading" : "Compare materials",
		"matSel.compare" : "compare (table)",
		"matSel.comparePlot" : "compare (plot)",
		"matSel.abort" : "cancel",
		"matSel.clickToRemove" : "click to remove",
		"matSel.select" : "Please choose further materials for comparison.",
		"matSel.maxSel" : "A maximum of {0} materials can be compared.", // contains placeholders in curly brackets which are dynamically filled using String.format
		"matSel.loading" : "Loading...",
		
		"appAreaWidgetToggle":"Select visualization:",
		"showTagCloud":"Show as tag cloud",
		"showImageGrid":"Show as image grid",
		"tagCloud.search" : "Search in application areas",
		
		"userMatClasses.headerWhenNoHistory": "Exemplary material classes",
		
		/* labels required by the researh overview widget */
		"ro.ltm" : "less than a minute",
		"ro.minute": " minute",
		"ro.hour": "hour",
		"ro.day" : "day",
		"ro.plural" : "s",
		"ro.ago" : "ago",
		"ro.tmpl" : "{0} {1}{2} {3}", // contains placeholders (see above)
		"ro.result" : "result",
		"ro.results" : "results",
		"ro.furtherResults" : "... and {0} further filters", // contains placeholders (see above)
		"ro.mail.query.subject":"My search query in the Material Hub",
		"ro.mail.query.content":"My search query from {0} with {1} result(s):\n{2}", // contains placeholders (see above)
		"ro.mail.queries.subject": "My search queries in the Material Hub",
		"ro.mail.savedQuery.subject":"My saved search query in the Material Hub",
		"ro.mail.savedQuery.content": "Search query from {0} with {1} result(s):\n{2}", // contains placeholders (see above)
		"ro.mail.savedQueries.subject":"My saved searc hquery in the Material Hub",
		"ro.mail.savedQueries.content": "Search query from {0} with {1} result(s):\n{2}\n\n", // contains placeholders (see above)
		"ro.mail.bookmarks.subject":"My bookmarks within the Material Hub",
		"ro.mail.pageVisits.subject":"My visited materials in the Material Hub",
		
		"history.types.bookmark" : "Bookmark",
		"history.types.pagevisit" : "Entry",
		"history.types.query" : "Query",
		"history.types.all" : "Entries",
		"history.notification.added" : "added to your search history.",
		"history.notification.removed" : "removed from your search history.",
		"history.error.disabled": "Unable to perform this action because personalization cookies are deactivated.",
		
		"addBookmark" : "add bookmark",
		"removeBookmark" : "remove bookmark",
		"removeAllBookmarks" : "remove all bookmarks",
		"showAllBookmarks" : "show all bookmarks",
		"showAllBookmarksCollapse" : "show less bookmarks",
		"compare" : "compare",
		"share" : "share",
		"removeFromHistory" : "remove from history",
		"removeVisits" : "remove visits",
		"showVisits" : "show all visits",
		"showVisitsCollapse" : "show less visits",
		"removeQuery" : "remove query",
		"removeQueries": "remove all queries",
		"removeAllQueries" : "remove all queries",
		"showAllQueries" : "show all queries",
		"showAllQueriesCollapse" : "show less queries",
		"showQueries": "show all queries",
		"showQueriesCollapse": "show less queries",
		"loggedInAs": "logged in as",
		"clearHistory": "clear user history",
		"showProfile" : "edit user profile",
		"showResearchOverview": "show the whole research history",
		
		"sd.cpp":"use the following material properties",
		"sd.cpp.selectProps":"Please select one to three material properties, that should be shown for searh results.",
		
		"dym": "Did you mean...",
		
		"simMaterialsSearch.noresults":"No results for the defined material properties and deviations found!",
		
		"matedit.autosave": "The material description has automatically been saved as '{0}'.",
		
		/* labels for material classes */
		"Verbundwerkstoffe": "composite",
		"Werkstoffe" : "materials",
		"Metalle" : "metals",
		"Eisenmetalle" : "ferrous metals",
		"Stähle": "steels",
		"Bau- und Konstruktionsstähle": "structural steels",
		"Unlegierte Baustähle": "unalloyed structural steels",
		"Feinkornbaustähle":"fine-grained structural steels",
		"Vergütungsstähle":"Q&T steels",
		"Einsatzstähle":"case-hardened steels",
		"Nitrierstähle":"nitrided steels",
		"Federstähle":"spring steels",
		"Warmfeste Stähle":"heat-resistant steels",
		"Kaltzähe Stähle":"cryogenic steels",
		"Nichtrostende Stähle":"stainless steels",
		"Automatenstähle":"machining steels",
		"Werkzeugstähle":"tool steels",
		"Kaltarbeitsstähle":"cold-work steels",
		"Warmarbeitsstähle":"hot-working steels",
		"Schnellarbeitsstähle":"high speed steels",
		"Kunststoffformenstähle":"plastic mould steels",
		"Eisengusswerkstoffe":"cast iron",
		"Stahlguss":"cast steel",
		"Weißes Gusseisen":"white cast iron",
		"Graues Gusseisen":"grey cast iron",
		"Sondergusseisen":"special cast iron",
		"Nichteisenmetalle":"non-ferrous metals",
		"Leichtmetalle":"light metals",
		"Schwermetalle":"heavy metals",
		"Edelmetalle":"noble metals",
		"Buntmetalle":"corroding heavy metals",
		"Weißmetalle":"white metal",
		"Nichtmetalle":"nonmetals",
		"Anorganisch":"inorganic",
		"Anorganisch-natürlich":"natural",
		"Anorganisch-synthetisch":"synthetical",
		"Keramik":"ceramics",
		"Silikatkeramik":"silicate ceramics",
		"Oxidkeramik":"oxide ceramics",
		"Nichtoxidkeramik":"non-oxide ceramics",
		"Gläser":"glasses",
		"Anorganische Bindemittel":"inorganic binder",
		"Organisch":"organic",
		"Organisch-natürlich":"natural",
		"Pflanzliche Stoffe":"herbal materials",
		"Tierische Stoffe":"animal materials",
		"Organisch-synthetisch":"synthetical",
		"Kunststoffe":"plastics",
		"Thermoplaste":"thermoplastics",
		"Thermoplastische Elastomere":"thermoplastic elastomers",
		"Duroplaste":"thermosetting plastics",
		"Elastomere":"elastomers",
		"Umgewandelte Naturstoffe":"transformed natural products",
		
		/* labels for generalized application areas */
		"Abdeckungen":"covers",
		"Abstandshalter":"spacers",
		"Abstreifer":"scraper",
		"Amboss":"anvil",
		"Antriebe":"drives",
		"Apparatebau":"apparatus engineering",
		"Architektur":"architecture",
		"Autoklav":"autoclave",
		"Automatisierung":"automation",
		"Balge":"bellows",
		"Bauwesen":"construction",
		"Behälter":"vessel",
		"Belüftung":"ventilation",
		"Bergbau":"mining",
		"Beschichtung":"coating",
		"Bohren":"drilling",
		"Brandschutz":"fire protection",
		"Chemieindustrie":"chemical industry",
		"Dekoration":"decoration",
		"Dichtungen":"seals",
		"Elektrik":"electrics",
		"Elektronik":"electronics",
		"Energietechnik":"power engineering",
		"Entflammbare Umgebungen":"flammable environments",
		"Explosionsschutz":"explosion protection",
		"Fahrzeugbau":"automotive industry",
		"Farbenindustrie":"paint industry",
		"Fender":"fender",
		"Filter":"filters",
		"Fördertechnik":"conveyor technology",
		"Formteile":"molded parts",
		"Führungen":"conducts",
		"Füllstutzen":"filling spouts",
		"Funktionsmodelle":"functional models",
		"Gartenbau":"horticulture",
		"Galvanik":"electroplating",
		"Gebäudetechnik":"building technology",
		"Geländer":"railings",
		"Getränkeindustrie":"beverage industry",
		"Gleitelemente":"sliding elements",
		"Haushalt":"household",
		"Hafenbau":"harbor construction",
		"Halbleiter":"semiconductors",
		"Hochdrucksysteme":"high-pressure systems",
		"Hydraulik":"hydraulics",
		"Hygieneartikel":"hygiene products",
		"industrielle Anwendungen":"industrial applications",
		"Innenausbau":"interior finishing",
		"Instrumentenbau":"instrument making",
		"Isolierung":"insulation",
		"Kanalisation":"sewerage",
		"Kaschieren":"lamination",
		"Kompressoren":"compressors",
		"Korrosionsschutz":"corrosion protection",
		"Kühlschränke":"refrigerators",
		"Kurzwaren":"haberdashery",
		"Lager": "bearings",
		"Laden- und Messebau":"store and exhibition stand construction",
		"Lackindustrie":"paint industry",
		"Landwirtschaft":"agriculture",
		"Lebensmittelkontakt":"food contact",
		"Lichttechnik":"lighting technology",
		"Luftfahrt":"aviation",
		"Maschinenbau":"mechanical engineering",
		"Mechanik":"mechanics",
		"Medizin":"medicine",
		"Militär":"military",
		"Mitnehmer":"drivers",
		"Möbelbau":"furniture construction",
		"Montage":"assembly",
		"Montageplatten": "mounting plates",
		"Nassbereiche":"wet areas",
		"Nuklearindustrie":"nuclear industry",
		"Offshore":"offshore",
		"Öl und Gas":"oil and gas",
		"Orthopädie":"orthopedics",
		"Outdoor":"outdoor",
		"Papierindustrie":"paper industry",
		"Pharmazie":"pharmacy",
		"Portionieren":"portioning",
		"Produktdesign":"product design",
		"Prototypenbau":"prototyping",
		"Pulverbeschichtung":"powder coating",
		"Pumpen":"pumps",
		"Raumfahrt":"spaceflight",
		"Reha":"rehabilitation",
		"Reinraum":"clean room",
		"Rollen":"rollers",
		"Sandstrahlen":"sandblasting",
		"Sanitär":"sanitary",
		"Schienen":"rails",
		"Schiffbau":"shipbuilding",
		"Schilder":"signs",
		"Schmuck":"jewelry",
		"Schnecken":"screws",
		"Schneidunterlagen":"cutting pads",
		"Schule und Kindergarten":"school and kindergarten",
		"Sicherheitstechnik":"safety engineering",
		"Siebdruck":"screen printing",
		"Spielplatzausstattung":"playground equipment",
		"Spielwaren":"toys",
		"Sport und Freizeit":"sports and leisure",
		"Spritzschutz":"splash guard",
		"Stahlindustrie":"steel industry",
		"Stempeln":"stamping",
		"Tanks":"tanks",
		"Technische Teile":"technical parts",
		"Textilindustrie":"textile industry",
		"Transportwesen":"transportation",
		"Trennwände":"partition walls",
		"Türen und Tore":"doors and gates",
		"Umlenkscheiben":"pulleys",
		"Umwelttechnik":"environmental technology",
		"Vakuumformen":"vacuum forming",
		"Verglasung":"glazing",
		"Verkleidungen":"cladding",
		"Verpackung":"packaging",
		"Verschleißschutz":"wear protection",
		"Wasser":"water",
		"Werbung":"advertising",
		"Wohnmobile":"caravans",
		"Zahnräder":"gear wheels",
		
		"food":"indication of suitability for food contact",
		"certificateByCountry": "Certificate by region",
		"certificate":"Certificate",
		
		"querySuggestions":"Query suggestions",
		"addFilter":"Add filter",
		"matClass":"material class",
		"placeholder":"placeholder",
		"symbolicImage":"symbolic image",
		"matImage":"material image"
	};
	
	try {
	if (propertyLabels != undefined) {
		Object.assign(localizedStrings, propertyLabels);
		propertyLabels = null;
	}
	}catch(E){console.error(E);}
	
	return {
		getLanguage : function(){
			return language;
		},
		getString : function(key){
			return localizedStrings[key] || key;
		}
	}
})();