/* English labels for material properties. */
let propertyLabels = {
    "applicationArea": "application area",
    "applicationAreaGeneral": "application area",
    "basicProperties": "basic properties",
    "category": "category",
    "cert": "certificate",
    "citation": "related scientific publication",
    "citationUrl": "related scientific publication (URL)",
    "dataDeliverer": "data deliverer",
    "dataDelivererID": "internal identifier of the data deliverer",
    "dataSheetUrl": "url of the data sheet of the supplier",
    "disclaimer": "disclaimer",
    "externalProperties": "external properties",
    "freeText": "Description",
    "imageUrl": "image of the material",
    "literature": "further reading",
    "name": "name",
    "obfuscate": "obfuscated Properties",
    "otherProps": "further Properties",
    "producer": "Producer",
    "producerID": "internal identifier of the producer",
    "supplier": "supplier",
    "supplierID": "internal identifier of the supplier",
    "usecases": "use cases",
    "abrasion": "abrasion",
    "abrasionLoss": "abrasion loss",
    "absorptionMoisture": "moisture absorption",
    "absorptionWater": "water absorption",
    "angleContact": "contact angle",
    "antiAdhesionProperties": "non-stick properties",
    "capacityDischargeElectrostatic": "electrostatic discharge capacity",
    "capacityThermal": "thermal capacity",
    "color": "color",
    "compositionChemical": "chemical composition (weight percent)",
    "compositionCompound": "compounds",
    "compressibility": "compressibility",
    "compressionCold": "cold compression value",
    "compressionHot": "hot creep",
    "compressionSet": "compression set",
    "conductivityElectrical": "electrical conductivity",
    "conductivityThermal": "thermal conductivity",
    "construction": "construction",
    "contentChlorideLeachable": "leachable chloride content",
    "contentChlorideTotal": "total chloride content",
    "contentFluorideTotal": "total fluoride content",
    "contentSilicate": "silicate content",
    "countThread": "thread count",
    "crossLinking": "cross linking",
    "deformationLoad": "deformation under load",
    "density": "density",
    "density_specificGravity": "specific gravity",
    "diameterFilament": "filament diameter",
    "dimension": "dimension",
    "dissipationFactorDielectric": "dielectric dissipation factor",
    "distribution": "distribution",
    "effectMode": "effect mode",
    "expansionThermalLinearCoefficient": "coefficient of linear thermal expansion",
    "flammability": "flammability",
    "flexibility": "flexibility",
    "flowRateMeltMass": "melt mass-flow rate",
    "flowRateMeltVolume": "melt volume-flow rate",
    "forceActor": "actuator force",
    "forceBreak": "breaking force",
    "frictionCoefficientDynamic": "coefficient of dynamic friction",
    "frictionCoefficientStatic": "coefficient of static friction",
    "hardness_ShoreA": "Shore hardness (type A)",
    "hardness_ShoreD": "Shore hardness (type D)",
    "hardness_RockwellE": "Rockwell hardness (E)",
    "hardness_RockwellC": "Rockwell hardness (C)",
    "hardness_RockwellM": "Rockwell hardness (M)",
    "hardness_RockwellR": "Rockwell hardness (R)",
    "hardness_Ball": "ball indentation hardness",
    "hardness_Brinell": "Brinell hardness",
    "hardness_IRHD": "IRHD hardness",
    "hardness_Janka": "Janka hardness",
    "hardness_Pencil": "hardness (pencil)",
    "hardnessChange": "change of hardness",
    "ignitionLoss": "loss on ignition",
    "increaseThickness": "thickness increase",
    "increaseWeight": "weight increase",
    "leakageRateSpecific": "specific leakage rate",
    "modulusElasticityCompressive": "compressive modulus of elasticity",
    "modulusElasticityFlexural": "flexural modulus of elasticity",
    "modulusElasticityTensile": "tensile modulus of elasticity",
    "nameAbbreviation": "abbreviation",
    "nameAlternative": "alternative naming",
    "nameLanguage": "name translation",
    "nameTrade": "trade name",
    "oxygenIndex": "oxygen index",
    "oxygenIndexLimiting": "limiting oxygen index",
    "permeabilityMagnetic": "magnetic permeability",
    "permittivityAbsolute": "absolute permittivity",
    "permittivityRelative": "relative permittivity",
    "pressureSurface": "surface pressure",
    "processManufacture": "manufacturing process",
    "purityGraphite": "purity level of graphite",
    "rangeTravel": "travel range",
    "rangeVoltage": "voltage range",
    "ratioPoisson": "Poisson's ratio",
    "reboundResilience": "rebound resilience",
    "recovery": "recovery",
    "recoveryCold": "cold recovery",
    "recoveryHot": "hot recovery",
    "resistanceAbrasionWet": "wet abrasion resistance",
    "resistanceArc": "arc resistance",
    "resistanceChemical": "chemical resistance",
    "resistanceCorrosion": "corrosion resistance",
    "resistanceElectricalSpecific": "specific electrical resistance",
    "resistanceOxidationGraphite": "oxidation resistance of graphite",
    "resistanceSurface": "surface resistance",
    "resistanceSurfaceSpecific": "specific surface resistance",
    "resistanceTrackingElectrical": "electrical tracking resistance",
    "resistanceVolume": "volume resistance",
    "resistanceVolumeSpecific": "specific volume resistance",
    "retractionTemperatureValue": "temperature retraction value",
    "roughnessAverageArithmetic": "arithmetic average roughness",
    "roughnessSquared": "root-mean-squared roughness",
    "roughnessDepthAveraged": "averaged roughness depth",
    "roughnessDepthMaximum": "maximal roughness depth",
    "shrinkageArea": "area shrinkage",
    "shrinkageLength": "linear length shrinkage",
    "shrinkageThickness": "thickness shrinkage",
    "shrinkage_radial": "radial shrinkage",
    "shrinkage_tangential": "tangential shrinkage",
    "shrinkage_TRRatio": "T\/R Ratio (shrinkage)",
    "shrinkage_volume": "volumetric shrinkage",
    "strainCompressiveBreakNominal": "nominal compressive strain at break",
    "strainCompressiveStrengthNominal": "nominal compressive strain at compressive strength",
    "strainCompressiveYieldNominal": "nominal compressive strain at yield",
    "strainFlexuralBreak": "flexural strain at break",
    "strainFlexuralStrength": "flexural strain at flexural strength",
    "strainTensileBreak": "tensile strain at break",
    "strainTensileBreakChange": "change of tensile strain at break",
    "strainTensileBreakNominal": "nominal tensile strain at break",
    "strainTensileCreep": "tensile creep strain",
    "strainTensileStrength": "tensile strain at tensile strength",
    "strainTensileYield": "tensile strain at yield",
    "strengthAdhesive": "adhesive strength",
    "strengthBursting": "bursting strength",
    "strengthCompressive": "compressive strength",
    "strengthDielectric": "dielectric strength",
    "strengthFlexural": "flexural strength",
    "strengthImpact": "impact strength",
    "strengthMinimumRequiredClassification": "minimum required strength classification",
    "strengthMinimumRequired": "minimum required strength",
    "strengthPullOffCoatings": "pull-off strength of coatings",
    "strengthShear": "shear strength",
    "strengthTensile": "tensile strength",
    "strengthTensileChange": "change of tensile strength",
    "strengthTensileFatigue": "tensile fatigue strength",
    "strengthTensileYield02": "yield strength 0,2 %",
    "stressCompressiveBreak": "compressive stress at break",
    "stressCompressiveStrain": "compressive stress at x % strain",
    "stressCompressiveYield": "compressive stress at yield",
    "stressFlexuralBreak": "flexural stress at break",
    "stressFlexuralDeflectionConventional": "flexural stress at conventional deflection",
    "stressPlateau": "plateau stress",
    "stressResidual": "residual stress",
    "stressTensileBreak": "tensile stress at break",
    "stressTensileStrain": "tensile stress",
    "stressTensileYield": "tensile stress at yield",
    "temperatureAnnealingSoft": "soft annealing temperature",
    "temperatureApplication": "application temperature",
    "temperatureApplicationShortTerm": "short-term application temperature",
    "temperatureBrittleness": "brittleness temperature",
    "temperatureCoatingWorkpiece": "coating workpiece temperature",
    "temperatureDeflectionLoad": "heat deflection temperature",
    "temperatureDeformationCold": "cold deformation temperature",
    "temperatureGlassTransition": "glass transition temperature",
    "temperatureHardening": "hardening temperature",
    "temperatureIgnitionGlowWire": "glow wire ignition temperature",
    "temperatureMelting": "melting temperature",
    "temperatureMeltingCrystallineGrain": "crystalline melting temperature",
    "temperatureSurrounding": "surrounding temperature",
    "temperatureSwitching": "switching temperature",
    "temperatureVicatSoftening": "vicat softening temperature",
    "thickness": "thickness",
    "thicknessCoating": "coating thickness",
    "toughnessFracture": "tear strength",
    "tr10value": "TR10 value",
    "volumeChange": "change of volume",
    "weightArea": "surface weight"
}